# Generated by Django 4.2.11 on 2026-03-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_chat', '0001_initial'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='snippet',
            field=models.ForeignKey(blank=True, help_text='Optionally link this chat session to a specific code snippet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='snippets.codesnippet'),
        ),
    ]
